# Generated by Django 6.0.3 on 2026-05-09 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_af',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ar_dz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_be',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_bs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ckb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_cs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_da',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_dsb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_en_au',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_eo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_es_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_es_co',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_es_mx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_es_ni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_es_ve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_et',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_eu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_fy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_gd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_gl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_hr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_hsb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_hu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_io',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_is',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_kab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_km',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_lb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_lv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_mk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_mn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_nb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_nn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_sl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_sq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_sr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_sr_latn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_tg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_tk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_tt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_udm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_vi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
